import type {
  Alert,
  Client,
  Contract,
  DemoDocument,
  DocumentSet,
  Invoice,
  Milestone,
  MilestoneKey,
  Order,
  Plant,
  Product,
  Task,
} from './types';

export const clients: Client[] = [
  {
    id: 'cli-northstar',
    name: 'Northstar Frozen Foods LLC',
    country: 'Estados Unidos',
    taxId: 'US-EIN 84-0001842',
    address: '440 Harbor Avenue, Wilmington, DE',
    paymentTerm: 'Crédito Directo',
    creditDays: 30,
    status: 'Activo',
    contacts: [
      {
        id: 'c1',
        name: 'Emily Carter',
        role: 'Comercial',
        email: 'emily.carter@example.com',
        phone: '+1 555 010 114',
      },
      {
        id: 'c2',
        name: 'Daniel Brooks',
        role: 'Logística',
        email: 'daniel.brooks@example.com',
        phone: '+1 555 010 228',
      },
      {
        id: 'c3',
        name: 'Ava Wilson',
        role: 'Documentación/Cobranza',
        email: 'ava.wilson@example.com',
        phone: '+1 555 010 332',
      },
    ],
    documentRequirements: [
      'BL Original',
      'Commercial Invoice',
      'Packing List',
      'NOPIC para orgánicos',
    ],
    qualityRequirements: [
      'COA por lote',
      'Microbiología completa',
      'Detección de metales',
    ],
  },
  {
    id: 'cli-nordlicht',
    name: 'Nordlicht Naturkost GmbH',
    country: 'Alemania',
    taxId: 'DE 000 184 295',
    address: 'Speicherweg 18, Hamburg',
    paymentTerm: 'CAD Bancario',
    creditDays: 0,
    status: 'Activo',
    contacts: [
      {
        id: 'c4',
        name: 'Lena Fischer',
        role: 'Comercial',
        email: 'lena.fischer@example.com',
        phone: '+49 555 012 410',
      },
      {
        id: 'c5',
        name: 'Jonas Weber',
        role: 'Logística',
        email: 'jonas.weber@example.com',
        phone: '+49 555 012 511',
      },
      {
        id: 'c6',
        name: 'Mia Wagner',
        role: 'Documentación/Cobranza',
        email: 'mia.wagner@example.com',
        phone: '+49 555 012 612',
      },
    ],
    documentRequirements: [
      'EUR.1',
      'COI para orgánicos',
      'BL telex release',
      'Factura comercial',
    ],
    qualityRequirements: [
      'COA',
      'Pesticidas EU 396/2005',
      'Trazabilidad de campo',
    ],
  },
  {
    id: 'cli-pacific',
    name: 'Pacific Pantry Trading K.K.',
    country: 'Japón',
    taxId: 'JP-CN 0100-00-18421',
    address: '2-18 Minato, Yokohama',
    paymentTerm: 'CAD Directo',
    creditDays: 0,
    status: 'En revisión',
    contacts: [
      {
        id: 'c7',
        name: 'Hana Mori',
        role: 'Comercial',
        email: 'hana.mori@example.com',
        phone: '+81 555 018 714',
      },
      {
        id: 'c8',
        name: 'Ren Sato',
        role: 'Logística',
        email: 'ren.sato@example.com',
        phone: '+81 555 018 815',
      },
      {
        id: 'c9',
        name: 'Yui Kato',
        role: 'Documentación/Cobranza',
        email: 'yui.kato@example.com',
        phone: '+81 555 018 916',
      },
    ],
    documentRequirements: [
      'Certificado fitosanitario',
      'BL Original',
      'Packing List bilingüe',
    ],
    qualityRequirements: [
      'COA por lote',
      'Inspección visual AQL',
      'Declaración GMO',
    ],
  },
];

export const plants: Plant[] = [
  {
    id: 'pla-andes',
    name: 'Procesadora Andes Sur SpA',
    city: 'San Fernando',
    region: 'O’Higgins',
    taxId: '76.000.184-2',
    exportCode: 'SAG-CHL-184',
    status: 'Habilitada',
    contacts: [
      {
        id: 'p1',
        name: 'Camila Ríos',
        role: 'Comercial',
        email: 'camila.rios@example.com',
        phone: '+56 2 5550 0184',
      },
      {
        id: 'p2',
        name: 'Matías Soto',
        role: 'Logística',
        email: 'matias.soto@example.com',
        phone: '+56 2 5550 0284',
      },
      {
        id: 'p3',
        name: 'Laura Vidal',
        role: 'Documentación/Cobranza',
        email: 'laura.vidal@example.com',
        phone: '+56 2 5550 0384',
      },
    ],
    permanentDocuments: [
      {
        id: 'pd1',
        name: 'Resolución sanitaria',
        expiresAt: '2027-04-30',
        state: 'Vigente',
      },
      {
        id: 'pd2',
        name: 'Certificado BRCGS',
        expiresAt: '2026-10-04',
        state: 'Por vencer',
      },
      {
        id: 'pd3',
        name: 'Certificación orgánica',
        expiresAt: '2027-01-15',
        state: 'Vigente',
      },
    ],
  },
  {
    id: 'pla-valle',
    name: 'Frío Valle Central Ltda.',
    city: 'Curicó',
    region: 'Maule',
    taxId: '77.000.295-6',
    exportCode: 'SAG-CHL-295',
    status: 'Condicional',
    contacts: [
      {
        id: 'p4',
        name: 'Tomás Leiva',
        role: 'Comercial',
        email: 'tomas.leiva@example.com',
        phone: '+56 2 5550 0495',
      },
      {
        id: 'p5',
        name: 'Antonia Pérez',
        role: 'Logística',
        email: 'antonia.perez@example.com',
        phone: '+56 2 5550 0595',
      },
      {
        id: 'p6',
        name: 'Diego Mora',
        role: 'Documentación/Cobranza',
        email: 'diego.mora@example.com',
        phone: '+56 2 5550 0695',
      },
    ],
    permanentDocuments: [
      {
        id: 'pd4',
        name: 'Resolución sanitaria',
        expiresAt: '2027-02-28',
        state: 'Vigente',
      },
      {
        id: 'pd5',
        name: 'Certificado HACCP',
        expiresAt: '2026-09-25',
        state: 'Por vencer',
      },
      {
        id: 'pd6',
        name: 'Registro FDA',
        expiresAt: '2026-08-31',
        state: 'Vencido',
      },
    ],
  },
  {
    id: 'pla-patagonia',
    name: 'Congelados Patagonia Pacífico S.A.',
    city: 'Osorno',
    region: 'Los Lagos',
    taxId: '96.000.406-1',
    exportCode: 'SAG-CHL-406',
    status: 'Habilitada',
    contacts: [
      {
        id: 'p7',
        name: 'Fernanda Paz',
        role: 'Comercial',
        email: 'fernanda.paz@example.com',
        phone: '+56 2 5550 0706',
      },
      {
        id: 'p8',
        name: 'Nicolás Lagos',
        role: 'Logística',
        email: 'nicolas.lagos@example.com',
        phone: '+56 2 5550 0806',
      },
      {
        id: 'p9',
        name: 'Josefina Silva',
        role: 'Documentación/Cobranza',
        email: 'josefina.silva@example.com',
        phone: '+56 2 5550 0906',
      },
    ],
    permanentDocuments: [
      {
        id: 'pd7',
        name: 'Resolución sanitaria',
        expiresAt: '2027-06-30',
        state: 'Vigente',
      },
      {
        id: 'pd8',
        name: 'Certificado IFS Food',
        expiresAt: '2027-03-18',
        state: 'Vigente',
      },
      {
        id: 'pd9',
        name: 'Certificación Kosher',
        expiresAt: '2026-11-02',
        state: 'Vigente',
      },
    ],
  },
];

export const products: Product[] = [
  {
    id: 'pro-blue',
    code: 'IQF-BLU-W',
    program: 'Berries 2026/27',
    species: 'Arándano',
    condition: 'Convencional',
    type: 'Whole',
    caliber: '12–18 mm',
    quality: 'Grade A',
    status: 'Activo',
  },
  {
    id: 'pro-blue-org',
    code: 'IQF-BLU-ORG',
    program: 'Orgánico 2026/27',
    species: 'Arándano',
    condition: 'Orgánico',
    type: 'Whole',
    caliber: '12–18 mm',
    quality: 'Grade A',
    status: 'Activo',
  },
  {
    id: 'pro-rasp',
    code: 'IQF-RAS-B',
    program: 'Berries 2026/27',
    species: 'Frambuesa',
    condition: 'Convencional',
    type: 'Broken',
    caliber: 'Natural',
    quality: 'Grade B',
    status: 'Activo',
  },
  {
    id: 'pro-straw-org',
    code: 'IQF-STR-ORG',
    program: 'Orgánico 2026/27',
    species: 'Frutilla',
    condition: 'Orgánico',
    type: 'Diced 10×10',
    caliber: '10 mm',
    quality: 'Grade A',
    status: 'Activo',
  },
  {
    id: 'pro-cherry',
    code: 'IQF-CHE-H',
    program: 'Carozos 2026/27',
    species: 'Cereza',
    condition: 'Convencional',
    type: 'Halves',
    caliber: '20–28 mm',
    quality: 'Grade A',
    status: 'Activo',
  },
  {
    id: 'pro-broccoli',
    code: 'IQF-BRO-F',
    program: 'Vegetales 2026',
    species: 'Brócoli',
    condition: 'Convencional',
    type: 'Florets',
    caliber: '20–40 mm',
    quality: 'Grade A',
    status: 'Temporada cerrada',
  },
];

export const contracts: Contract[] = [
  {
    id: 'con-26041',
    code: 'BORRADOR',
    clientId: 'cli-pacific',
    po: 'PO-PP-26091',
    incoterm: 'CFR Yokohama',
    currency: 'USD',
    issuedAt: '2026-09-15',
    state: 'Borrador',
    orderIds: [],
    attachments: ['Especificación de calidad.xlsx'],
    lines: [
      {
        id: 'cl1',
        productId: 'pro-blue',
        packaging: 'Caja 10 × 1 kg, bolsa azul',
        contractedKg: 22000,
        assignedKg: 0,
        pricePerKg: 3.285,
      },
      {
        id: 'cl2',
        productId: 'pro-rasp',
        packaging: 'Caja bulk 10 kg, liner PE',
        contractedKg: 20000,
        assignedKg: 0,
        pricePerKg: 2.74,
      },
    ],
  },
  {
    id: 'con-26037',
    code: 'EVX-CT-26037',
    clientId: 'cli-northstar',
    po: 'PO-NS-7782',
    incoterm: 'Ex Dock Philadelphia',
    currency: 'USD',
    issuedAt: '2026-07-28',
    state: 'Emitido',
    orderIds: ['ord-26091', 'ord-26093', 'ord-26095'],
    attachments: ['Contrato firmado.pdf', 'PO cliente.pdf'],
    lines: [
      {
        id: 'cl3',
        productId: 'pro-straw-org',
        packaging: 'Caja 4 × 2,5 kg, bolsa transparente',
        contractedKg: 66000,
        assignedKg: 44000,
        pricePerKg: 3.96,
      },
      {
        id: 'cl4',
        productId: 'pro-broccoli',
        packaging: 'Caja bulk 10 kg, liner azul',
        contractedKg: 22000,
        assignedKg: 22000,
        pricePerKg: 1.875,
      },
    ],
  },
  {
    id: 'con-26032',
    code: 'EVX-CT-26032',
    clientId: 'cli-nordlicht',
    po: 'PO-NN-1048',
    incoterm: 'CIF Hamburg',
    currency: 'EUR',
    issuedAt: '2026-06-12',
    state: 'Casi completo',
    orderIds: ['ord-26092', 'ord-26094', 'ord-26088'],
    attachments: [
      'Contrato firmado.pdf',
      'Anexo orgánico.pdf',
      'Ficha técnica.pdf',
    ],
    lines: [
      {
        id: 'cl5',
        productId: 'pro-blue-org',
        packaging: 'Caja 10 × 1 kg, bolsa compostable',
        contractedKg: 44000,
        assignedKg: 42000,
        pricePerKg: 4.425,
      },
      {
        id: 'cl6',
        productId: 'pro-cherry',
        packaging: 'Caja 5 × 2 kg, bolsa neutra',
        contractedKg: 22000,
        assignedKg: 22000,
        pricePerKg: 3.315,
      },
    ],
  },
];

const milestoneLabels: Array<[MilestoneKey, string]> = [
  ['plant', 'Planta confirmada'],
  ['booking', 'Booking'],
  ['instructions', 'Instructivo emitido'],
  ['loading', 'Carga'],
  ['departure', 'Zarpe'],
  ['documents', 'Documentos'],
  ['arrival', 'Arribo'],
  ['delivery', 'Entrega'],
  ['payment', 'Pago'],
  ['closure', 'Cierre'],
];

const makeMilestones = (completed: number, dates: string[]): Milestone[] =>
  milestoneLabels.map(([key, label], index) => ({
    key,
    label,
    state:
      index < completed
        ? 'Completado'
        : index === completed
          ? 'Actual'
          : 'Pendiente',
    date: index < completed ? dates[index] : undefined,
  }));

const baseOperational = (prefix: string, advanced = false) => [
  {
    id: `${prefix}-o1`,
    label: 'Producción confirmada con planta',
    owner: 'Operaciones',
    dueAt: '2026-09-15',
    state: advanced ? ('Aprobado' as const) : ('En proceso' as const),
  },
  {
    id: `${prefix}-o2`,
    label: 'Disponibilidad de cámara y despacho',
    owner: 'Planta',
    dueAt: '2026-09-16',
    state: advanced ? ('Recibido' as const) : ('Pendiente' as const),
  },
  {
    id: `${prefix}-o3`,
    label: 'Coordinación de transporte',
    owner: 'Logística',
    dueAt: '2026-09-18',
    state: advanced ? ('Aprobado' as const) : ('Pendiente' as const),
  },
  {
    id: `${prefix}-o4`,
    label: 'VGM y matriz de carga validados',
    owner: 'Documentación',
    dueAt: '2026-09-19',
    state: advanced ? ('Aprobado' as const) : ('Pendiente' as const),
  },
];

const baseDocuments = (prefix: string, advanced = false) => [
  {
    id: `${prefix}-d1`,
    label: 'Commercial Invoice',
    owner: 'Everex',
    dueAt: '2026-09-19',
    state: advanced ? ('Aprobado' as const) : ('Borrador' as const),
  },
  {
    id: `${prefix}-d2`,
    label: 'Packing List',
    owner: 'Planta',
    dueAt: '2026-09-19',
    state: advanced ? ('Aprobado' as const) : ('En revisión' as const),
  },
  {
    id: `${prefix}-d3`,
    label: 'BL Final',
    owner: 'Forwarder',
    dueAt: '2026-09-22',
    state: advanced ? ('Recibido' as const) : ('Pendiente' as const),
  },
  {
    id: `${prefix}-d4`,
    label: 'Certificado de origen / orgánico',
    owner: 'Documentación',
    dueAt: '2026-09-22',
    state: advanced ? ('Aprobado' as const) : ('Pendiente' as const),
  },
];

const bookingEmpty = {
  forwarder: 'Por definir',
  carrier: 'Por definir',
  booking: 'Pendiente',
  vessel: '—',
  voyage: '—',
  stacking: '—',
  originPort: 'San Antonio, CL',
  destinationPort: '—',
  docsCutoff: '—',
  reeferCutoff: '—',
  temperature: '-18 °C',
  ventilation: 'Cerrada',
};
const loadingEmpty = {
  transporter: 'Por definir',
  driver: '—',
  truckPlate: '—',
  trailerPlate: '—',
  container: 'Pendiente',
  seal: '—',
  thermograph: '—',
  netKg: 0,
  grossKg: 0,
  vgmKg: 0,
  actualAt: '—',
};

export const initialOrders: Order[] = [
  {
    id: 'ord-26091',
    code: 'FCL-26091',
    contractId: 'con-26037',
    clientId: 'cli-northstar',
    destination: 'Philadelphia, USA',
    incoterm: 'FOB San Antonio',
    macroStatus: 'Pendiente',
    stage: 'Confirmación de planta',
    dates: {
      frc: '2026-09-15',
      ftp: '2026-09-18',
      etd: '2026-09-24',
      eta: '2026-10-22',
    },
    items: [
      {
        id: 'oi1',
        productId: 'pro-straw-org',
        plantId: 'pla-andes',
        packaging: 'Caja 4 × 2,5 kg, bolsa transparente',
        kilograms: 22000,
        pallets: 20,
        boxes: 2200,
        lot: 'STR-ORG-2609-A',
        organic: true,
      },
    ],
    booking: bookingEmpty,
    loading: loadingEmpty,
    milestones: makeMilestones(0, []),
    operationalChecklist: baseOperational('91'),
    documentChecklist: baseDocuments('91'),
    alertIds: ['al-booking', 'al-nopic'],
    invoiceId: undefined,
    archived: false,
    history: [
      {
        id: 'h91-1',
        at: '2026-09-14 16:20',
        title: 'Pedido / FCL creado',
        detail: 'Generado desde contrato EVX-CT-26037.',
        actor: 'Administrador Everex',
      },
    ],
  },
  {
    id: 'ord-26092',
    code: 'FCL-26092',
    contractId: 'con-26032',
    clientId: 'cli-nordlicht',
    destination: 'Hamburg, Alemania',
    incoterm: 'CIF Hamburg',
    macroStatus: 'Pendiente',
    stage: 'Instructivo pendiente',
    dates: {
      frc: '2026-09-13',
      ftp: '2026-09-16',
      etd: '2026-09-18',
      eta: '2026-10-15',
    },
    items: [
      {
        id: 'oi2',
        productId: 'pro-blue-org',
        plantId: 'pla-andes',
        packaging: 'Caja 10 × 1 kg, bolsa compostable',
        kilograms: 20000,
        pallets: 20,
        boxes: 2000,
        lot: 'BLU-ORG-2609-C',
        organic: true,
      },
    ],
    booking: {
      forwarder: 'BlueRoute Logistics',
      carrier: 'Aurora Ocean Lines',
      booking: 'AOL-0184926',
      vessel: 'MV Southern Light',
      voyage: 'SL-0926E',
      stacking: '2026-09-16 08:00–18:00',
      originPort: 'San Antonio, CL',
      destinationPort: 'Hamburg, DE',
      docsCutoff: '2026-09-16 12:00',
      reeferCutoff: '2026-09-17 06:00',
      temperature: '-18 °C',
      ventilation: 'Cerrada',
    },
    loading: loadingEmpty,
    milestones: makeMilestones(2, ['12 sep', '14 sep']),
    operationalChecklist: baseOperational('92'),
    documentChecklist: baseDocuments('92'),
    alertIds: ['al-instruction', 'al-cold', 'al-coi'],
    invoiceId: undefined,
    archived: false,
    history: [
      {
        id: 'h92-1',
        at: '2026-09-14 11:05',
        title: 'Booking registrado',
        detail: 'Reserva AOL-0184926 confirmada.',
        actor: 'Operaciones',
      },
    ],
  },
  {
    id: 'ord-26093',
    code: 'FCL-26093',
    contractId: 'con-26037',
    clientId: 'cli-northstar',
    destination: 'Newark, USA',
    incoterm: 'CFR Newark',
    macroStatus: 'En Curso',
    stage: 'Coordinación de carga',
    dates: {
      frc: '2026-09-10',
      ftp: '2026-09-14',
      etd: '2026-09-21',
      eta: '2026-10-19',
    },
    items: [
      {
        id: 'oi3',
        productId: 'pro-straw-org',
        plantId: 'pla-valle',
        packaging: 'Caja 4 × 2,5 kg, bolsa transparente',
        kilograms: 22000,
        pallets: 20,
        boxes: 2200,
        lot: 'STR-ORG-2608-F',
        organic: true,
      },
    ],
    booking: {
      forwarder: 'Compass Freight',
      carrier: 'Pacific Meridian',
      booking: 'PM-774921',
      vessel: 'MV Cerro Azul',
      voyage: 'CA-0921N',
      stacking: '2026-09-19 09:00–17:00',
      originPort: 'San Antonio, CL',
      destinationPort: 'Newark, US',
      docsCutoff: '2026-09-18 15:00',
      reeferCutoff: '2026-09-20 04:00',
      temperature: '-18 °C',
      ventilation: 'Cerrada',
    },
    loading: loadingEmpty,
    milestones: makeMilestones(3, ['9 sep', '11 sep', '14 sep']),
    operationalChecklist: baseOperational('93'),
    documentChecklist: baseDocuments('93'),
    alertIds: ['al-nopic'],
    invoiceId: undefined,
    archived: false,
    history: [
      {
        id: 'h93-1',
        at: '2026-09-14 14:35',
        title: 'Instructivo emitido',
        detail: 'Versión 1 enviada a planta y transporte.',
        actor: 'Administrador Everex',
      },
    ],
  },
  {
    id: 'ord-26094',
    code: 'FCL-26094',
    contractId: 'con-26032',
    clientId: 'cli-pacific',
    destination: 'Yokohama, Japón',
    incoterm: 'CFR Yokohama',
    macroStatus: 'En Curso',
    stage: 'Documentación previa',
    dates: {
      frc: '2026-09-08',
      ftp: '2026-09-12',
      etd: '2026-09-17',
      eta: '2026-10-24',
    },
    items: [
      {
        id: 'oi4',
        productId: 'pro-blue',
        plantId: 'pla-patagonia',
        packaging: 'Caja 10 × 1 kg, bolsa azul',
        kilograms: 22000,
        pallets: 20,
        boxes: 2200,
        lot: 'BLU-2608-J',
        organic: false,
      },
    ],
    booking: {
      forwarder: 'Andes Cargo Network',
      carrier: 'Horizon Container Lines',
      booking: 'HCL-550842',
      vessel: 'MV Cordillera',
      voyage: 'COR-117W',
      stacking: '2026-09-15 12:00–20:00',
      originPort: 'San Antonio, CL',
      destinationPort: 'Yokohama, JP',
      docsCutoff: '2026-09-15 16:00',
      reeferCutoff: '2026-09-16 05:00',
      temperature: '-18 °C',
      ventilation: 'Cerrada',
    },
    loading: loadingEmpty,
    milestones: makeMilestones(3, ['8 sep', '10 sep', '12 sep']),
    operationalChecklist: baseOperational('94'),
    documentChecklist: baseDocuments('94'),
    alertIds: [],
    invoiceId: undefined,
    archived: false,
    history: [
      {
        id: 'h94-1',
        at: '2026-09-12 10:10',
        title: 'Instructivo emitido',
        detail: 'Datos validados por planta.',
        actor: 'Operaciones',
      },
    ],
  },
  {
    id: 'ord-26095',
    code: 'FCL-26095',
    contractId: 'con-26037',
    clientId: 'cli-northstar',
    destination: 'Philadelphia, USA',
    incoterm: 'Ex Dock Philadelphia',
    macroStatus: 'Despachado',
    stage: 'En tránsito · documentos',
    dates: {
      frc: '2026-08-28',
      ftp: '2026-09-02',
      etd: '2026-09-07',
      eta: '2026-10-04',
    },
    items: [
      {
        id: 'oi5',
        productId: 'pro-broccoli',
        plantId: 'pla-valle',
        packaging: 'Caja bulk 10 kg, liner azul',
        kilograms: 22000,
        pallets: 20,
        boxes: 2200,
        lot: 'BRO-2608-XD',
        organic: false,
      },
    ],
    booking: {
      forwarder: 'Compass Freight',
      carrier: 'Pacific Meridian',
      booking: 'PM-770195',
      vessel: 'MV Coastal Pine',
      voyage: 'CP-0907N',
      stacking: '2026-09-04 08:00–18:00',
      originPort: 'San Antonio, CL',
      destinationPort: 'Philadelphia, US',
      docsCutoff: '2026-09-04 14:00',
      reeferCutoff: '2026-09-05 05:00',
      temperature: '-18 °C',
      ventilation: 'Cerrada',
    },
    loading: {
      transporter: 'Transportes Cordón Sur',
      driver: 'Mauricio Vega',
      truckPlate: 'TR-KL-42',
      trailerPlate: 'SR-PX-18',
      container: 'PMRU 418406-2',
      seal: 'EVX-771842',
      thermograph: 'TG-26095-04',
      netKg: 22000,
      grossKg: 23784.5,
      vgmKg: 27740,
      actualAt: '2026-09-04 15:42',
    },
    milestones: makeMilestones(5, [
      '28 ago',
      '30 ago',
      '2 sep',
      '4 sep',
      '7 sep',
    ]),
    operationalChecklist: baseOperational('95', true),
    documentChecklist: baseDocuments('95'),
    alertIds: [],
    customsBroker: 'Harbor Customs Services Inc. (demo)',
    invoiceId: 'inv-26095',
    archived: false,
    history: [
      {
        id: 'h95-1',
        at: '2026-09-07 22:10',
        title: 'Zarpe confirmado',
        detail: 'MV Coastal Pine · voyage CP-0907N.',
        actor: 'Operaciones',
      },
      {
        id: 'h95-2',
        at: '2026-09-10 09:05',
        title: 'Pago parcial registrado',
        detail: 'Abono USD 24.750,000 aplicado a factura.',
        actor: 'Cobranza',
      },
    ],
  },
  {
    id: 'ord-26088',
    code: 'FCL-26088',
    contractId: 'con-26032',
    clientId: 'cli-nordlicht',
    destination: 'Rotterdam, Países Bajos',
    incoterm: 'CIF Rotterdam',
    macroStatus: 'Cerrado',
    stage: 'Expediente archivado',
    dates: {
      frc: '2026-06-18',
      ftp: '2026-06-23',
      etd: '2026-06-29',
      eta: '2026-07-27',
    },
    items: [
      {
        id: 'oi6',
        productId: 'pro-cherry',
        plantId: 'pla-patagonia',
        packaging: 'Caja 5 × 2 kg, bolsa neutra',
        kilograms: 22000,
        pallets: 20,
        boxes: 2200,
        lot: 'CHE-2606-H',
        organic: false,
      },
    ],
    booking: {
      forwarder: 'BlueRoute Logistics',
      carrier: 'Aurora Ocean Lines',
      booking: 'AOL-0178421',
      vessel: 'MV Baltic Dawn',
      voyage: 'BD-0629E',
      stacking: '2026-06-26 08:00–18:00',
      originPort: 'San Antonio, CL',
      destinationPort: 'Rotterdam, NL',
      docsCutoff: '2026-06-26 12:00',
      reeferCutoff: '2026-06-28 04:00',
      temperature: '-18 °C',
      ventilation: 'Cerrada',
    },
    loading: {
      transporter: 'Logística Ruta Fría',
      driver: 'Felipe Araya',
      truckPlate: 'VF-PL-62',
      trailerPlate: 'RT-HJ-77',
      container: 'AOLU 295184-4',
      seal: 'EVX-761094',
      thermograph: 'TG-26088-02',
      netKg: 22000,
      grossKg: 23810,
      vgmKg: 27750,
      actualAt: '2026-06-26 14:18',
    },
    milestones: makeMilestones(10, [
      '18 jun',
      '20 jun',
      '23 jun',
      '26 jun',
      '29 jun',
      '2 jul',
      '27 jul',
      '29 jul',
      '12 ago',
      '14 ago',
    ]),
    operationalChecklist: baseOperational('88', true),
    documentChecklist: baseDocuments('88', true),
    alertIds: [],
    invoiceId: 'inv-26088',
    archived: true,
    history: [
      {
        id: 'h88-1',
        at: '2026-08-14 12:00',
        title: 'Pedido cerrado',
        detail: 'Pago total, entrega y expediente verificados.',
        actor: 'Administrador Everex',
      },
    ],
  },
];

export const initialDocuments: DemoDocument[] = [
  {
    id: 'doc-95-book',
    orderId: 'ord-26095',
    name: 'Booking',
    kind: 'Externo',
    state: 'Aprobado',
    required: true,
    version: 'Final',
    updatedAt: '30 ago',
    setIds: ['set-agency', 'set-broker'],
  },
  {
    id: 'doc-95-inst',
    orderId: 'ord-26095',
    name: 'Instructivo de Embarque',
    kind: 'Interno',
    state: 'Enviado',
    required: true,
    version: 'v2',
    updatedAt: '2 sep',
    setIds: ['set-agency'],
  },
  {
    id: 'doc-95-prof',
    orderId: 'ord-26095',
    name: 'Proforma',
    kind: 'Interno',
    state: 'Aprobado',
    required: false,
    version: 'v1',
    updatedAt: '28 ago',
    setIds: ['set-client'],
  },
  {
    id: 'doc-95-pack',
    orderId: 'ord-26095',
    name: 'Packing List',
    kind: 'Interno',
    state: 'Aprobado',
    required: true,
    version: 'v3',
    updatedAt: '5 sep',
    setIds: ['set-client', 'set-agency', 'set-bank', 'set-broker'],
  },
  {
    id: 'doc-95-inv',
    orderId: 'ord-26095',
    name: 'Commercial Invoice',
    kind: 'Interno',
    state: 'Aprobado',
    required: true,
    version: 'v2',
    updatedAt: '7 sep',
    setIds: ['set-client', 'set-agency', 'set-bank', 'set-broker'],
  },
  {
    id: 'doc-95-bld',
    orderId: 'ord-26095',
    name: 'BL Draft',
    kind: 'Externo',
    state: 'En revisión',
    required: false,
    version: 'v2',
    updatedAt: '13 sep',
    setIds: ['set-client', 'set-bank', 'set-broker'],
  },
  {
    id: 'doc-95-blf',
    orderId: 'ord-26095',
    name: 'BL Final',
    kind: 'Externo',
    state: 'Pendiente',
    required: true,
    version: '—',
    updatedAt: '—',
    setIds: ['set-client', 'set-bank', 'set-broker'],
  },
  {
    id: 'doc-95-coa',
    orderId: 'ord-26095',
    name: 'COA',
    kind: 'Externo',
    state: 'Recibido',
    required: true,
    version: 'Final',
    updatedAt: '6 sep',
    setIds: ['set-client', 'set-broker'],
  },
  {
    id: 'doc-95-cert',
    orderId: 'ord-26095',
    name: 'Certificado fitosanitario',
    kind: 'Externo',
    state: 'En revisión',
    required: true,
    version: 'Draft',
    updatedAt: '11 sep',
    setIds: ['set-client', 'set-agency', 'set-broker'],
  },
  {
    id: 'doc-95-ship',
    orderId: 'ord-26095',
    name: 'Shipment Advice',
    kind: 'Interno',
    state: 'Enviado',
    required: true,
    version: 'v1',
    updatedAt: '8 sep',
    setIds: ['set-client', 'set-broker'],
  },
  {
    id: 'doc-91-nopic',
    orderId: 'ord-26091',
    name: 'NOPIC',
    kind: 'Externo',
    state: 'Pendiente',
    required: true,
    version: '—',
    updatedAt: '—',
    setIds: [],
  },
  {
    id: 'doc-92-coi',
    orderId: 'ord-26092',
    name: 'COI',
    kind: 'Externo',
    state: 'Pendiente',
    required: true,
    version: '—',
    updatedAt: '—',
    setIds: [],
  },
  {
    id: 'doc-93-nopic',
    orderId: 'ord-26093',
    name: 'NOPIC',
    kind: 'Externo',
    state: 'En proceso',
    required: true,
    version: 'Draft',
    updatedAt: '14 sep',
    setIds: [],
  },
  {
    id: 'doc-94-inst',
    orderId: 'ord-26094',
    name: 'Instructivo de Embarque',
    kind: 'Interno',
    state: 'Enviado',
    required: true,
    version: 'v1',
    updatedAt: '12 sep',
    setIds: [],
  },
  {
    id: 'doc-88-file',
    orderId: 'ord-26088',
    name: 'Expediente documental completo',
    kind: 'Interno',
    state: 'Aprobado',
    required: true,
    version: 'Archivado',
    updatedAt: '14 ago',
    setIds: [],
  },
];

export const initialDocumentSets: DocumentSet[] = [
  {
    id: 'set-client',
    orderId: 'ord-26095',
    name: 'Set Cliente',
    documentIds: [
      'doc-95-prof',
      'doc-95-pack',
      'doc-95-inv',
      'doc-95-bld',
      'doc-95-blf',
      'doc-95-coa',
      'doc-95-cert',
      'doc-95-ship',
    ],
    state: 'Preparando',
    recipients: ['imports@example.com', 'documents@example.com'],
  },
  {
    id: 'set-agency',
    orderId: 'ord-26095',
    name: 'Set Agencia de Aduanas',
    documentIds: [
      'doc-95-book',
      'doc-95-inst',
      'doc-95-pack',
      'doc-95-inv',
      'doc-95-cert',
    ],
    state: 'Listo',
    recipients: ['operations@example.com'],
    approvedAt: '15 sep · 10:42',
  },
  {
    id: 'set-bank',
    orderId: 'ord-26095',
    name: 'Set Banco/Cobranza',
    documentIds: ['doc-95-pack', 'doc-95-inv', 'doc-95-bld', 'doc-95-blf'],
    state: 'Preparando',
    recipients: ['tradefinance@example.com'],
  },
  {
    id: 'set-broker',
    orderId: 'ord-26095',
    name: 'Set Customs Broker',
    documentIds: [
      'doc-95-book',
      'doc-95-pack',
      'doc-95-inv',
      'doc-95-bld',
      'doc-95-blf',
      'doc-95-coa',
      'doc-95-cert',
      'doc-95-ship',
    ],
    state: 'Enviado',
    recipients: ['clearance@example.com'],
    approvedAt: '12 sep · 16:08',
    sentAt: '12 sep · 16:16',
  },
];

export const initialAlerts: Alert[] = [
  {
    id: 'al-booking',
    orderId: 'ord-26091',
    title: 'Booking pendiente',
    detail: 'Falta reserva naviera para FCL-26091.',
    severity: 'Crítica',
    dueLabel: 'ETD − 7',
    resolved: false,
  },
  {
    id: 'al-instruction',
    orderId: 'ord-26092',
    title: 'Instructivo pendiente',
    detail: 'Debe emitirse para confirmar la carga.',
    severity: 'Crítica',
    dueLabel: 'ETD − 2',
    resolved: false,
  },
  {
    id: 'al-cold',
    orderId: 'ord-26092',
    title: 'Certificado de frío SAG',
    detail: 'Sin recepción desde planta.',
    severity: 'Alta',
    dueLabel: 'ETD − 2',
    resolved: false,
  },
  {
    id: 'al-nopic',
    orderId: 'ord-26091',
    title: 'NOPIC orgánico USA',
    detail: 'Requerido antes del zarpe.',
    severity: 'Crítica',
    dueLabel: 'ETD − 4',
    resolved: false,
  },
  {
    id: 'al-coi',
    orderId: 'ord-26092',
    title: 'COI orgánico Europa',
    detail: 'Pendiente validación documental.',
    severity: 'Alta',
    dueLabel: 'ETD − 3',
    resolved: false,
  },
];

export const initialTasks: Task[] = [
  {
    id: 'task-1',
    orderId: 'ord-26091',
    title: 'Confirmar producción con planta',
    owner: 'Camila',
    dueLabel: 'Hoy · 10:00',
    completed: false,
  },
  {
    id: 'task-2',
    orderId: 'ord-26091',
    title: 'Solicitar booking',
    owner: 'Matías',
    dueLabel: 'Hoy · 12:00',
    completed: false,
  },
  {
    id: 'task-3',
    orderId: 'ord-26095',
    title: 'Revisar Draft BL',
    owner: 'Laura',
    dueLabel: 'Hoy · 15:30',
    completed: false,
  },
  {
    id: 'task-4',
    orderId: 'ord-26088',
    title: 'Confirmar entrega',
    owner: 'Matías',
    dueLabel: 'Mañana',
    completed: true,
  },
  {
    id: 'task-5',
    orderId: 'ord-26088',
    title: 'Revisar expediente para cierre',
    owner: 'Laura',
    dueLabel: '18 sep',
    completed: true,
  },
];

export const initialInvoices: Invoice[] = [
  {
    id: 'inv-26095',
    code: 'EXP-260184',
    orderId: 'ord-26095',
    clientId: 'cli-northstar',
    issuedAt: '2026-09-07',
    dueAt: '2026-10-07',
    paymentTerm: 'Crédito Directo',
    currency: 'USD',
    total: 41250,
    paid: 24750,
    state: 'Parcial',
  },
  {
    id: 'inv-26088',
    code: 'EXP-260141',
    orderId: 'ord-26088',
    clientId: 'cli-nordlicht',
    issuedAt: '2026-06-29',
    dueAt: '2026-07-05',
    paymentTerm: 'CAD Bancario',
    currency: 'EUR',
    total: 72930,
    paid: 72930,
    state: 'Pagada',
  },
  {
    id: 'inv-26094',
    code: 'EXP-260180',
    orderId: 'ord-26094',
    clientId: 'cli-pacific',
    issuedAt: '2026-09-12',
    dueAt: '2026-09-17',
    paymentTerm: 'CAD Directo',
    currency: 'USD',
    total: 72270,
    paid: 0,
    state: 'Pendiente',
  },
];
